name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.3
      with:
          versionSpec: '5.2.x'
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.3
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }}
    - name: Persist artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Func.AspNetCore.${{ steps.gitversion.outputs.NuGetVersionV2 }}
        path: |
          Func.AspNetCore/bin/Release/Func.AspNetCore.${{ steps.gitversion.outputs.NuGetVersionV2 }}.nupkg
          Func.AspNet/bin/Release/Func.AspNet.${{ steps.gitversion.outputs.NuGetVersionV2 }}.nupkg
        
